<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <groupId>dev.geo</groupId>
    <artifactId>admin</artifactId>
    <version>0.1.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>admin</name>
    <description>A modern admin platform built with Spring Boot</description>
    <url>https://admin.geoearth.dev</url>

    <modules>
        <module>admin-server</module>
        <module>admin-framework</module>
        <module>admin-module-system</module>
    </modules>
    <properties>
        <java.version>17</java.version>
        <springdoc.version>3.0.3</springdoc.version>
        <mybatis-plus.version>3.5.17</mybatis-plus.version>
        <mybatis-plus-join.version>1.5.9</mybatis-plus-join.version>
        <druid.version>1.2.28</druid.version>
        <lombok.version>1.18.46</lombok.version>
        <hutool.version>5.8.47</hutool.version>
        <poi.version>5.5.1</poi.version>
        <yauaa.version>8.2.0</yauaa.version>
        <fastjson.version>2.0.64</fastjson.version>
    </properties>

    <!-- 依赖声明 -->
    <dependencyManagement>
        <dependencies>
            <!-- ==================== 内部模块 ==================== -->
            <dependency>
                <groupId>dev.geo</groupId>
                <artifactId>admin-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.geo</groupId>
                <artifactId>admin-mybatis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.geo</groupId>
                <artifactId>admin-config</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.geo</groupId>
                <artifactId>admin-security</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.geo</groupId>
                <artifactId>admin-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- Excel 导入导出组件 -->
            <dependency>
                <groupId>dev.geo</groupId>
                <artifactId>admin-excel</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.geo</groupId>
                <artifactId>admin-framework</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.geo</groupId>
                <artifactId>admin-module-system</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- ==================== 第三方组件 ==================== -->
            <!-- 阿里数据库连接池 -->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-4-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            <!-- 编辑器并构建工具 -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <!-- spring-doc -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-scalar</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <!--  MyBatis-Plus 依赖配置 -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-bom</artifactId>
                <version>${mybatis-plus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- MyBatis-Plus-Join 连表查询 -->
            <dependency>
                <groupId>com.github.yulichang</groupId>
                <artifactId>mybatis-plus-join-boot-starter</artifactId>
                <version>${mybatis-plus-join.version}</version>
            </dependency>

            <!-- util-->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-bom</artifactId>
                <version>${hutool.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- excel工具 -->
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi.version}</version>
            </dependency>

            <!-- 解析客户端操作系统、浏览器等 -->
            <dependency>
                <groupId>nl.basjes.parse.useragent</groupId>
                <artifactId>yauaa</artifactId>
                <version>${yauaa.version}</version>
            </dependency>
            <!-- 阿里JSON解析器 -->
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson.version}</version>
            </dependency>

        </dependencies>

    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
