-- Restore only icons changed by this operation.
USE `admin_platform`;
START TRANSACTION;
UPDATE sys_menu SET icon = 'system' WHERE id = 1 AND icon = 'lucide:settings';
UPDATE sys_menu SET icon = 'monitor' WHERE id = 2 AND icon = 'lucide:activity';
UPDATE sys_menu SET icon = 'tool' WHERE id = 3 AND icon = 'lucide:wrench';
UPDATE sys_menu SET icon = 'user' WHERE id = 100 AND icon = 'lucide:user-round';
UPDATE sys_menu SET icon = 'peoples' WHERE id = 101 AND icon = 'lucide:users-round';
UPDATE sys_menu SET icon = 'tree-table' WHERE id = 102 AND icon = 'lucide:list-tree';
UPDATE sys_menu SET icon = 'tree' WHERE id = 103 AND icon = 'lucide:network';
UPDATE sys_menu SET icon = 'post' WHERE id = 104 AND icon = 'lucide:contact-round';
UPDATE sys_menu SET icon = 'dict' WHERE id = 105 AND icon = 'lucide:book-open';
UPDATE sys_menu SET icon = 'edit' WHERE id = 106 AND icon = 'lucide:settings-2';
UPDATE sys_menu SET icon = 'message' WHERE id = 107 AND icon = 'lucide:bell';
UPDATE sys_menu SET icon = 'log' WHERE id = 108 AND icon = 'lucide:logs';
UPDATE sys_menu SET icon = 'online' WHERE id = 109 AND icon = 'lucide:monitor-check';
UPDATE sys_menu SET icon = 'job' WHERE id = 110 AND icon = 'lucide:clock';
UPDATE sys_menu SET icon = 'druid' WHERE id = 111 AND icon = 'lucide:database';
UPDATE sys_menu SET icon = 'server' WHERE id = 112 AND icon = 'lucide:server';
UPDATE sys_menu SET icon = 'redis' WHERE id = 113 AND icon = 'lucide:database-zap';
UPDATE sys_menu SET icon = 'redis-list' WHERE id = 114 AND icon = 'lucide:list';
UPDATE sys_menu SET icon = 'build' WHERE id = 115 AND icon = 'lucide:panels-top-left';
UPDATE sys_menu SET icon = 'code' WHERE id = 116 AND icon = 'lucide:code-xml';
UPDATE sys_menu SET icon = 'swagger' WHERE id = 117 AND icon = 'lucide:cable';
UPDATE sys_menu SET icon = 'form' WHERE id = 500 AND icon = 'lucide:file-clock';
UPDATE sys_menu SET icon = 'logininfor' WHERE id = 501 AND icon = 'lucide:log-in';
COMMIT;
